(() => {
const canvas=document.getElementById("gameCanvas"),ctx=canvas.getContext("2d"),gameWrap=document.getElementById("gameWrap");
const startScreen=document.getElementById("startScreen"),gameOverScreen=document.getElementById("gameOverScreen"),startForm=document.getElementById("startForm"),restartBtn=document.getElementById("restartBtn"),departmentInput=document.getElementById("departmentInput"),nameInput=document.getElementById("nameInput"),scoreText=document.getElementById("scoreText"),hpText=document.getElementById("hpText"),waveText=document.getElementById("waveText"),weaponText=document.getElementById("weaponText"),playerInfo=document.getElementById("playerInfo"),finalInfo=document.getElementById("finalInfo");
const W=420,H=760; canvas.width=W; canvas.height=H;
const state={running:false,gameOver:false,score:0,wave:1,lastTime:0,enemyTimer:0,itemTimer:0,shotTimer:0,touchActive:false,touchX:0,stars:[],bullets:[],enemies:[],items:[],floatingTexts:[],keys:{},playerName:"",department:"",player:null};
function resetState(){state.running=false;state.gameOver=false;state.score=0;state.wave=1;state.lastTime=0;state.enemyTimer=0;state.itemTimer=0;state.shotTimer=0;state.touchActive=false;state.touchX=0;state.bullets=[];state.enemies=[];state.items=[];state.floatingTexts=[];state.player={x:W/2,y:H-84,w:34,h:34,speed:280,hp:5,maxHp:5,weapon:"기본",weaponLevel:1,shield:0,fireCooldown:.18,hitFlash:0};state.stars=Array.from({length:46},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.8+.5,v:Math.random()*28+16}));updateHud()}
function updateHud(){scoreText.textContent=String(state.score);hpText.textContent=`${state.player.hp}${state.player.shield>0?" +실드":""}`;waveText.textContent=String(state.wave);weaponText.textContent=state.player.weapon;playerInfo.textContent=state.playerName?`${state.department||"부서 미입력"} · ${state.playerName}`:"플레이어 미입력"}
function lockScroll(locked){document.documentElement.style.overflow=locked?"hidden":"";document.body.style.overflow=locked?"hidden":""}
function startGame(){resetState();state.playerName=(nameInput.value||"").trim();state.department=(departmentInput.value||"").trim();updateHud();startScreen.classList.add("hidden");gameOverScreen.classList.add("hidden");state.running=true;lockScroll(true);requestAnimationFrame(loop)}
function finishGame(){state.running=false;state.gameOver=true;lockScroll(false);finalInfo.textContent=`${state.department||"부서 미입력"} ${state.playerName||"익명"} · 최종 점수 ${state.score}점`;gameOverScreen.classList.remove("hidden")}
function spawnFloating(text,x,y,color="#fff"){state.floatingTexts.push({text,x,y,color,life:.8})}
function shoot(){const p=state.player;if(p.weaponLevel<=1)state.bullets.push({x:p.x,y:p.y-20,vx:0,vy:-430,r:5,type:"sanitizer"});else if(p.weaponLevel===2){state.bullets.push({x:p.x-9,y:p.y-18,vx:-35,vy:-430,r:5,type:"bubble"},{x:p.x+9,y:p.y-18,vx:35,vy:-430,r:5,type:"bubble"})}else{state.bullets.push({x:p.x,y:p.y-18,vx:0,vy:-450,r:6,type:"spray"},{x:p.x-14,y:p.y-18,vx:-80,vy:-420,r:4,type:"spray"},{x:p.x+14,y:p.y-18,vx:80,vy:-420,r:4,type:"spray"})}}
function spawnEnemy(){const roll=Math.random();let type="bacteria";if(roll>.72)type="virus";if(roll>.93)type="superbug";const enemy={type,x:30+Math.random()*(W-60),y:-24,w:28,h:28,vx:0,vy:80+Math.random()*45+state.wave*8,hp:1,value:10,wobble:Math.random()*Math.PI*2};if(type==="virus"){enemy.hp=2;enemy.value=20;enemy.vx=(Math.random()>.5?1:-1)*(35+Math.random()*28)}else if(type==="superbug"){enemy.hp=5;enemy.value=50;enemy.w=38;enemy.h=38;enemy.vy=62+state.wave*5}state.enemies.push(enemy)}
function spawnItem(){const kinds=["shield","heal","weapon"],kind=kinds[Math.floor(Math.random()*kinds.length)];state.items.push({kind,x:30+Math.random()*(W-60),y:-20,w:22,h:22,vy:110})}
function circleRectHit(cx,cy,r,obj){const tx=Math.max(obj.x-obj.w/2,Math.min(cx,obj.x+obj.w/2)),ty=Math.max(obj.y-obj.h/2,Math.min(cy,obj.y+obj.h/2)),dx=cx-tx,dy=cy-ty;return dx*dx+dy*dy<=r*r}
function rectHit(a,b){return a.x-a.w/2<b.x+b.w/2&&a.x+a.w/2>b.x-b.w/2&&a.y-a.h/2<b.y+b.h/2&&a.y+a.h/2>b.y-b.h/2}
function damagePlayer(){const p=state.player;if(p.shield>0){p.shield--;spawnFloating("실드!",p.x,p.y-10,"#7ff0b9")}else{p.hp--;p.hitFlash=.18;spawnFloating("-1",p.x,p.y-10,"#ff7d7d")}updateHud();if(p.hp<=0)finishGame()}
function handleItem(item){const p=state.player;if(item.kind==="shield"){p.shield=Math.min(2,p.shield+1);spawnFloating("실드 획득",item.x,item.y,"#7ff0b9")}else if(item.kind==="heal"){p.hp=Math.min(p.maxHp,p.hp+1);spawnFloating("회복",item.x,item.y,"#7ff0b9")}else{p.weaponLevel=Math.min(3,p.weaponLevel+1);p.weapon=p.weaponLevel===1?"기본":p.weaponLevel===2?"버블 샷":"확산 분사";spawnFloating("무기 강화",item.x,item.y,"#6ec6ff")}updateHud()}
function getGameX(clientX){const rect=canvas.getBoundingClientRect();return (clientX-rect.left)*(canvas.width/rect.width)}
function roundRectFill(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();ctx.fill()}
function update(dt){const p=state.player;p.hitFlash=Math.max(0,p.hitFlash-dt);if(state.keys["arrowleft"]||state.keys["a"])p.x-=p.speed*dt;if(state.keys["arrowright"]||state.keys["d"])p.x+=p.speed*dt;if(state.touchActive){const dx=state.touchX-p.x;p.x+=dx*Math.min(1,dt*8)}p.x=Math.max(24,Math.min(W-24,p.x));state.shotTimer+=dt;if(state.shotTimer>=p.fireCooldown){state.shotTimer=0;shoot()}state.enemyTimer+=dt;const enemyGap=Math.max(.35,1-state.wave*.05);if(state.enemyTimer>=enemyGap){state.enemyTimer=0;spawnEnemy()}state.itemTimer+=dt;if(state.itemTimer>=7){state.itemTimer=0;spawnItem()}const targetWave=1+Math.floor(state.score/160);if(targetWave!==state.wave){state.wave=targetWave;updateHud();spawnFloating(`WAVE ${state.wave}`,W/2,H/2,"#6ec6ff")}state.stars.forEach(s=>{s.y+=s.v*dt;if(s.y>H){s.y=-2;s.x=Math.random()*W}});state.bullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt});state.bullets=state.bullets.filter(b=>b.y>-30&&b.x>-30&&b.x<W+30);state.enemies.forEach(e=>{e.y+=e.vy*dt;if(e.type==="virus")e.x+=Math.sin(e.y*.03+e.wobble)*e.vx*dt});state.enemies=state.enemies.filter(e=>e.y<H+50);state.items.forEach(i=>i.y+=i.vy*dt);state.items=state.items.filter(i=>i.y<H+30);for(let bi=state.bullets.length-1;bi>=0;bi--){const b=state.bullets[bi];for(let ei=state.enemies.length-1;ei>=0;ei--){const e=state.enemies[ei];if(circleRectHit(b.x,b.y,b.r,e)){state.bullets.splice(bi,1);e.hp-=b.type==="spray"?2:1;if(e.hp<=0){state.score+=e.value;spawnFloating(`+${e.value}`,e.x,e.y,"#7ff0b9");state.enemies.splice(ei,1);updateHud()}break}}}for(let ei=state.enemies.length-1;ei>=0;ei--){if(rectHit(p,state.enemies[ei])){state.enemies.splice(ei,1);damagePlayer()}}for(let ii=state.items.length-1;ii>=0;ii--){if(rectHit(p,state.items[ii])){const item=state.items[ii];state.items.splice(ii,1);handleItem(item)}}state.floatingTexts.forEach(f=>{f.y-=26*dt;f.life-=dt});state.floatingTexts=state.floatingTexts.filter(f=>f.life>0)}
function drawPlayer(p){ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle=p.hitFlash>0?"#ff9a9a":"#17366f";roundRectFill(-12,-10,24,28,6);ctx.fillStyle="#dff2ff";roundRectFill(-7,-18,14,8,3);ctx.fillRect(-2,-24,4,7);ctx.fillRect(2,-24,8,3);ctx.fillStyle="#6ec6ff";ctx.fillRect(-2,-2,4,10);ctx.fillRect(-5,1,10,4);ctx.fillStyle="#87b7ff";ctx.fillRect(-16,-4,4,10);ctx.fillRect(12,-4,4,10);ctx.fillStyle="#dff2ff";ctx.fillRect(-8,18,4,5);ctx.fillRect(4,18,4,5);ctx.globalAlpha=.88;ctx.fillStyle="#9fe7ff";ctx.beginPath();ctx.arc(18,-10,8,0,Math.PI*2);ctx.fill();ctx.fillStyle="#dffaff";ctx.beginPath();ctx.arc(15,-13,2.4,0,Math.PI*2);ctx.fill();if(p.shield>0){ctx.strokeStyle="rgba(127,240,185,.9)";ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,2,24,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);if(e.type==="bacteria"){ctx.fillStyle="#9bff7f";ctx.beginPath();ctx.arc(0,0,12,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#d8ffd1";ctx.lineWidth=2;for(let a=0;a<8;a++){const ang=Math.PI*2*a/8;ctx.beginPath();ctx.moveTo(Math.cos(ang)*10,Math.sin(ang)*10);ctx.lineTo(Math.cos(ang)*16,Math.sin(ang)*16);ctx.stroke()}}else if(e.type==="virus"){ctx.fillStyle="#bf9bff";ctx.beginPath();ctx.arc(0,0,12,0,Math.PI*2);ctx.fill();ctx.fillStyle="#efe4ff";for(let a=0;a<6;a++){const ang=Math.PI*2*a/6;ctx.beginPath();ctx.arc(Math.cos(ang)*7,Math.sin(ang)*7,2.2,0,Math.PI*2);ctx.fill()}}else{ctx.fillStyle="#ffb36e";roundRectFill(-16,-16,32,32,9);ctx.fillStyle="#ffe1c2";ctx.fillRect(-4,-8,8,16);ctx.fillRect(-8,-4,16,8);ctx.strokeStyle="#fff2e1";ctx.lineWidth=2;ctx.strokeRect(-17,-17,34,34)}ctx.restore()}
function drawBullet(b){ctx.save();ctx.translate(b.x,b.y);if(b.type==="sanitizer"){ctx.fillStyle="#6ec6ff";ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fill()}else if(b.type==="bubble"){ctx.fillStyle="#a5efff";ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fill();ctx.fillStyle="#dffbff";ctx.beginPath();ctx.arc(-1.6,-1.6,1.8,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle="#b7f4ff";roundRectFill(-3,-7,6,14,3)}ctx.restore()}
function drawItem(i){ctx.save();ctx.translate(i.x,i.y);if(i.kind==="shield"){ctx.fillStyle="#7ff0b9";ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(10,-4);ctx.lineTo(7,10);ctx.lineTo(0,14);ctx.lineTo(-7,10);ctx.lineTo(-10,-4);ctx.closePath();ctx.fill()}else if(i.kind==="heal"){ctx.fillStyle="#ff8f8f";ctx.fillRect(-3,-10,6,20);ctx.fillRect(-10,-3,20,6)}else{ctx.fillStyle="#6ec6ff";roundRectFill(-9,-9,18,18,4);ctx.fillStyle="#e8f7ff";ctx.fillRect(-2,-6,4,12);ctx.fillRect(-6,-2,12,4)}ctx.restore()}
function drawFloatingText(f){ctx.save();ctx.globalAlpha=Math.max(0,Math.min(1,f.life));ctx.fillStyle=f.color;ctx.font="bold 16px sans-serif";ctx.textAlign="center";ctx.fillText(f.text,f.x,f.y);ctx.restore()}
function render(){ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#102244");g.addColorStop(1,"#091226");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle="rgba(255,255,255,.75)";state.stars.forEach(s=>{ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()});ctx.strokeStyle="rgba(255,255,255,.08)";ctx.lineWidth=2;for(let y=-20;y<H+30;y+=46){ctx.beginPath();ctx.moveTo(W/2,y+(state.lastTime*.18%46));ctx.lineTo(W/2,y+20+(state.lastTime*.18%46));ctx.stroke()}state.items.forEach(drawItem);state.bullets.forEach(drawBullet);state.enemies.forEach(drawEnemy);drawPlayer(state.player);state.floatingTexts.forEach(drawFloatingText)}
function loop(ts){if(!state.running)return;if(!state.lastTime)state.lastTime=ts;const dt=Math.min(.033,(ts-state.lastTime)/1000);state.lastTime=ts;update(dt);render();if(state.running)requestAnimationFrame(loop)}
startForm.addEventListener("submit",e=>{e.preventDefault();startGame()});
restartBtn.addEventListener("click",()=>{gameOverScreen.classList.add("hidden");startScreen.classList.remove("hidden");lockScroll(false)});
window.addEventListener("keydown",e=>{state.keys[e.key.toLowerCase()]=true;if(["arrowleft","arrowright"," ","a","d"].includes(e.key.toLowerCase()))e.preventDefault()},{passive:false});
window.addEventListener("keyup",e=>{state.keys[e.key.toLowerCase()]=false});
canvas.addEventListener("pointerdown",e=>{if(!state.running)return;e.preventDefault();state.touchActive=true;state.touchX=getGameX(e.clientX)},{passive:false});
canvas.addEventListener("pointermove",e=>{if(!state.touchActive||!state.running)return;e.preventDefault();state.touchX=getGameX(e.clientX)},{passive:false});
window.addEventListener("pointerup",()=>{state.touchActive=false});
canvas.addEventListener("touchstart",e=>{if(!state.running)return;e.preventDefault();const t=e.touches[0];if(!t)return;state.touchActive=true;state.touchX=getGameX(t.clientX)},{passive:false});
canvas.addEventListener("touchmove",e=>{if(!state.touchActive||!state.running)return;e.preventDefault();const t=e.touches[0];if(!t)return;state.touchX=getGameX(t.clientX)},{passive:false});
canvas.addEventListener("touchend",e=>{if(state.running)e.preventDefault();state.touchActive=false},{passive:false});
["touchstart","touchmove"].forEach(type=>gameWrap.addEventListener(type,e=>{if(state.running)e.preventDefault()},{passive:false}));
resetState();render();
})();
